name: rogue
ghc-options: -O2 -Wall -fno-warn-orphans
dependencies:
  - base >= 4.14 && < 5
  - relude

  - websockets
  - wreq
  - wuss

  - aeson
  - aeson-pretty
  - apecs
  - astar
  - base64
  - containers
  - data-default
  - directory
  - fixed-vector
  - lens
  - megaparsec
  - MonadRandom
  - scotty
  - split
  - template-haskell
  - time
  - unliftio
  - vector
executable:
  main: Main.hs
  source-dirs: src
